name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Vault
        run: |
          echo "window.VAULT = {
            ghToken: '${{ secrets.GH_PAT }}',
            secKey: '${{ secrets.R2_SECRET_ACCESS_KEY }}',
            r2Bucket: '${{ secrets.R2_BUCKET_NAME }}',
            accId: '${{ vars.R2_ACCOUNT_ID }}',
            keyId: '${{ vars.R2_ACCESS_KEY_ID }}'
          };" > vault.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
