name: Deploy Dashboard

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Secrets into HTML files
        run: |
          # 全てのHTMLファイル（*.html）を対象に置換を実行します
          sed -i "s|__R2_ACC_ID__|${{ secrets.R2_ACCOUNT_ID }}|g" *.html
          sed -i "s|__R2_KEY_ID__|${{ secrets.R2_ACCESS_KEY_ID }}|g" *.html
          sed -i "s|__R2_SEC_KEY__|${{ secrets.R2_SECRET_ACCESS_KEY }}|g" *.html
          sed -i "s|__R2_BUCKET__|${{ vars.R2_BUCKET_NAME }}|g" *.html
          sed -i "s|__GH_TOKEN__|${{ secrets.GH_PAT }}|g" *.html
          sed -i "s|__GH_REPO__|${{ github.repository }}|g" *.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
